### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by 10045125** [Bilibili/DanmakuFlameMaster#100]
java.util.ConcurrentModificationException
	at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)
	at java.util.TreeMap$BoundedMap$BoundedIterator.stepForward(TreeMap.java:1485)
	at java.util.TreeMap$BoundedMap$BoundedKeySet$1.next(TreeMap.java:1547)
	at master.flame.danmaku.danmaku.model.android.Danmakus$DanmakuIterator.next(Danmakus.java:285)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.prepareCaches(CacheManagingDrawTask.java:589)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:444)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ctiao** [comment]
什么情况下出现

**Comment by 10045125** [comment]
这个是我的日志报告里面提交上来的。这里没有提示我的代码里面哪里出错了，我也不好定位。
