### ISSUE TITLE
DrawingCacheHolder.draw NullPointerException

### ISSUE THREAD

**Issue by 10045125** [Bilibili/DanmakuFlameMaster#101]
ava.lang.NullPointerException
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1139)
	at master.flame.danmaku.danmaku.model.android.DrawingCacheHolder.draw(DrawingCacheHolder.java:181)
	at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.draw(AndroidDisplayer.java:260)
	at master.flame.danmaku.danmaku.model.BaseDanmaku.draw(BaseDanmaku.java:178)
	at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer.draw(DanmakuRenderer.java:87)
	at master.flame.danmaku.controller.DrawTask.drawDanmakus(DrawTask.java:244)
	at master.flame.danmaku.controller.DrawTask.draw(DrawTask.java:160)
	at master.flame.danmaku.controller.CacheManagingDrawTask.draw(CacheManagingDrawTask.java:83)
	at master.flame.danmaku.controller.DrawHandler.draw(DrawHandler.java:560)
	at master.flame.danmaku.ui.widget.DanmakuSurfaceView.drawDanmakus(DanmakuSurfaceView.java:245)
	at master.flame.danmaku.controller.DrawHandler$2.run(DrawHandler.java:383)

**Comment by ctiao** [comment]
使用DanmakuView代替DanmakuSurfaceView

**Comment by 10045125** [comment]
貌似效率没有DanmakuSurfaceView高吧？

**Comment by ctiao** [comment]
>=api11系统上，开启硬件加速后比SurfaceView效率高

**Comment by 10045125** [comment]
请问硬件加速是手动开启，还是程序自动开启呢？谢谢！

**Comment by 10045125** [comment]
弹幕太多的情况下，如何实现弹幕丢弃呢，期待您的回复。

**Comment by ctiao** [comment]
可以通过DanmakuGlobalConfig.DEFAULT.setMaximumVisibleSizeInScreen(maxSize)设置弹幕密度

**Comment by ctiao** [comment]
硬件加速需要应用手动开启  有多种作用范围不同的方法

**Comment by 10045125** [comment]
DanmakuGlobalConfig.DEFAULT.setMaximumVisibleSizeInScreen(-1)这样会出现弹幕的层叠现象吗？或者说如何设置才会避免出现层叠？

**Comment by ctiao** [comment]
一般把数值设到10以下就可以，  讲究点可以根据View大小和字体大小 设置不同的值

**Comment by 10045125** [comment]
还有一个方式，能不能获取当前cache里面的大小，如果大于多少就不再往里面加弹幕了，如果可以，要如何实现呢？期待您的解答！谢谢！

**Comment by xingstarx** [comment]
com.github.ctiao:dfm:0.3.9  

report this

at master.flame.danmaku.b.a.a.a.a(AndroidDisplayer.java:277)
        at master.flame.danmaku.b.a.c.a(BaseDanmaku.java:194)
        at master.flame.danmaku.b.c.a.a.a(DanmakuRenderer.java:126)
        at master.flame.danmaku.a.u.a(DrawTask.java:304)
        at master.flame.danmaku.a.u.a(DrawTask.java:205)
        at master.flame.danmaku.a.a.a(CacheManagingDrawTask.java:106)
        at master.flame.danmaku.a.r.a(DrawHandler.java:589)
        at master.flame.danmaku.ui.widget.DanmakuView.onDraw(DanmakuView.java:310)
        at android.view.View.draw(View.java:15356)
        at android.view.View.updateDisplayListIfDirty(View.java:14246)
        at android.view.View.getDisplayList(View.java:14276)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
        at android.view.View.updateDisplayListIfDirty(View.java:14196)
        at android.view.View.getDisplayList(View.java:14276)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:272)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:278)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:317)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2857)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2694)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2318)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6443)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)

**Comment by ctiao** [comment]
使用0.4.0 @xingstarx

**Comment by xingstarx** [comment]
谢谢啊
