### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by guojilong** [Bilibili/DanmakuFlameMaster#112]
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at master.flame.danmaku.danmaku.model.android.DanmakuGlobalConfig.notifyConfigureChanged(DanmakuGlobalConfig.java:552)
	at master.flame.danmaku.danmaku.model.android.DanmakuGlobalConfig.setDanmakuStyle(DanmakuGlobalConfig.java:343)

**Comment by ctiao** [comment]
你是在多个线程频繁的调用 registerConfigChangedCallback 或 unregisterConfigChangedCallback 
并且修改弹幕设置吗？

**Comment by 10045125** [comment]
java.util.ConcurrentModificationException
	at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)
	at java.util.TreeMap$BoundedMap$BoundedIterator.stepForward(TreeMap.java:1485)
	at java.util.TreeMap$BoundedMap$BoundedKeySet$1.next(TreeMap.java:1547)
	at java.util.LinkedList.addAll(LinkedList.java:394)
	at java.util.LinkedList.&lt;init&gt;(LinkedList.java:261)
	at master.flame.danmaku.danmaku.model.android.Danmakus.subnew(Danmakus.java:184)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.prepareCaches(CacheManagingDrawTask.java:561)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:445)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)


这个问题我这也遇到过，应该是LinkedList是线程不安全的，能否使用ConcurrentLinkedQueue？
这个出现错误概率还比较高。

**Comment by 10045125** [comment]
建议涉及到多线程的List时候，使用线程安全的List会比较好。或者添加一个同步锁。

**Comment by ctiao** [comment]
对全局设置这样不频繁的插入与读取的列表 ，并没有考虑线程安全。  你可以自行修改下，提交一个pr。

**Comment by ctiao** [comment]
fixed 097854a4b3d45868eae26e684c184a00f72f1207
