### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 10045125** [Bilibili/DanmakuFlameMaster#115]
java.lang.IllegalArgumentException
	at android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
	at android.view.Surface.unlockCanvasAndPost(Surface.java:255)
	at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:844)
	at master.flame.danmaku.ui.widget.DanmakuSurfaceView.drawDanmakus(DanmakuSurfaceView.java:252)
	at master.flame.danmaku.controller.DrawHandler.updateInCurrentThread(DrawHandler.java:342)
	at master.flame.danmaku.controller.DrawHandler.handleMessage(DrawHandler.java:228)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ctiao** [comment]
用DanmakuView。

**Comment by brucetoo** [comment]
用DanmakuView?除了这个方法呢？ 一直是用的DanmakuSurfaceView,DanmakuView会体现的很卡

**Comment by 10045125** [comment]
如果达到60帧每秒是看着不卡的，还有就是调节速度

**Comment by brucetoo** [comment]
具体业务逻辑 不同，我这边是除了弹幕还有很多其他的自定义View动画可能同时并发执行，所以很体现对额不好，就是不知道IllegalArgumentException 是什么导致的，@ctiao

**Comment by ctiao** [comment]
大概在lockcanvas之后为unlock之前， surface被destroy了

**Comment by ctiao** [comment]
surface在surfaceview改变大小、进入后台之后都会被destroy
