### ISSUE TITLE
DrawTask 中，多处使用danmakuList，需要做同步，否则外部可能出现ConcurrentModificationException

### ISSUE THREAD

**Issue by MikeZu** [Bilibili/DanmakuFlameMaster#171]
DrawTask 中，多处使用danmakuList，需要做同步，否则外部可能出现ConcurrentModificationException

详细日志如下：

03-18 18:42:09.755 E/AndroidRuntime(31700): java.util.ConcurrentModificationException

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap$BoundedMap$BoundedIterator.stepForward(TreeMap.java:1485)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1513)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1511)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap.count(TreeMap.java:1656)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeMap$BoundedMap.size(TreeMap.java:1126)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.TreeSet.size(TreeSet.java:256)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.AbstractCollection.toArrayList(AbstractCollection.java:348)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.AbstractCollection.toArray(AbstractCollection.java:339)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at java.util.ArrayList.<init>(ArrayList.java:97)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at master.flame.danmaku.danmaku.model.android.Danmakus.subnew(Danmakus.java:184)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at master.flame.danmaku.controller.DrawTask.getVisibleDanmakusOnTime(DrawTask.java:215)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at master.flame.danmaku.controller.DrawHandler.getCurrentVisibleDanmakus(DrawHandler.java:722)

03-18 18:42:09.755 E/AndroidRuntime(31700): 	at master.flame.danmaku.ui.widget.DanmakuView.getCurrentVisibleDanmakus(DanmakuView.java:130)

**Comment by ctiao** [comment]
已修复 使用最新版本
