### ISSUE TITLE
couldn't find "libDFMACC.so"

### ISSUE THREAD

**Issue by BobBright** [Bilibili/DanmakuFlameMaster#177]
下载最新版本，安装demo，已启动就报这个无措。log如下，
04-01 17:53:39.870: E/AndroidRuntime(29636): FATAL EXCEPTION: main
04-01 17:53:39.870: E/AndroidRuntime(29636): Process: com.sample, PID: 29636
04-01 17:53:39.870: E/AndroidRuntime(29636): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sample-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libDFMACC.so"
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.Runtime.loadLibrary(Runtime.java:378)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.System.loadLibrary(System.java:998)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at master.flame.danmaku.ui.SkiaRedirector.SkStupidView.<clinit>(SkStupidView.java:42)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.reflect.Constructor.newInstance(Native Method)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.Activity.setContentView(Activity.java:2188)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at com.sample.MainActivity.onCreate(MainActivity.java:62)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.Activity.performCreate(Activity.java:6013)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.ActivityThread.access$1200(ActivityThread.java:158)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.os.Looper.loop(Looper.java:135)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at android.app.ActivityThread.main(ActivityThread.java:5564)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.reflect.Method.invoke(Native Method)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
04-01 17:53:39.870: E/AndroidRuntime(29636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by BobBright** [comment]
不好意思，可能是网路丢包了，重新下载了一下，可以正常使用了，打扰了。
