### ISSUE TITLE
NPE in v0.4.2

### ISSUE THREAD

**Issue by zourb** [Bilibili/DanmakuFlameMaster#178]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'master.flame.danmaku.danmaku.model.android.DrawingCacheHolder master.flame.danmaku.danmaku.model.android.DrawingCache.get()' on a null object reference
	at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.draw(Unknown Source)
	at master.flame.danmaku.danmaku.model.BaseDanmaku.draw(Unknown Source)
	at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer.draw(Unknown Source)
	at master.flame.danmaku.controller.DrawTask.drawDanmakus(Unknown Source)
	at master.flame.danmaku.controller.DrawTask.draw(Unknown Source)
	at master.flame.danmaku.controller.CacheManagingDrawTask.draw(Unknown Source)
	at master.flame.danmaku.controller.DrawHandler.draw(Unknown Source)
	at master.flame.danmaku.ui.widget.DanmakuView.onDraw(Unknown Source)
	at android.view.View.draw(View.java:15253)
	at android.view.View.updateDisplayListIfDirty(View.java:14189)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2580)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2402)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
```

**Comment by ctiao** [comment]
maven或jcenter 0.4.9已发布
