### ISSUE TITLE
IllegalArgumentException DanmakuSurfaceView android 4.3

### ISSUE THREAD

**Issue by xzwszl** [Bilibili/DanmakuFlameMaster#201]
at android.view.Surface.nativeUnlockCanvasAndPost(Surface.java)
at android.view.Surface.unlockCanvasAndPost(Surface.java:255)
at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:844)
。。。
The Exception occurs when unlockCanvasAndPost method is called. All on Android 4.3 phones.

**Comment by scottguosk** [comment]
同问，v0.4.6，master.flame.danmaku.ui.widget.DanmakuSurfaceView.f(DanmakuSurfaceView.java:285)这行代码报
java.lang.IllegalArgumentException
android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
的错误

**Comment by liwangdong** [comment]
在Android4.3的系统上，会大量出现该问题：
java.lang.IllegalArgumentException
	at android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
	at android.view.Surface.unlockCanvasAndPost(Surface.java:255)
	at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:844)
	at master.flame.danmaku.ui.widget.DanmakuSurfaceView.drawDanmakus(DanmakuSurfaceView.java:285)
	at master.flame.danmaku.controller.DrawHandler$2.run(DrawHandler.java:402)
