### ISSUE TITLE
使用过程中出现空指针异常

### ISSUE THREAD

**Issue by weizongwei5** [Bilibili/DanmakuFlameMaster#205]
```
java.lang.NullPointerException
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.clearCache(CacheManagingDrawTask.java:327)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.entryRemoved(CacheManagingDrawTask.java:318)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.evictAll(CacheManagingDrawTask.java:278)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.access$500(CacheManagingDrawTask.java:163)
	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:544)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)
```
代码如下：
```
//最终报错在这里
private long clearCache(BaseDanmaku oldValue) {
if (oldValue.cache.hasReferences()) {
                oldValue.cache.decreaseReference();
                oldValue.cache = null;
                return 0;
            }
                long size = sizeOf(oldValue);
                oldValue.cache.destroy();
                oldValue.cache = null;
                return size;
}
                                                       
        protected void entryRemoved(boolean evicted, Ba
            if (oldValue.cache != null) {              
                IDrawingCache<?> cache = oldValue.cache
                long releasedSize = clearCache(oldValue
                if (releasedSize <= 0) return;         
                mRealSize -= releasedSize;             
                mCachePool.release((DrawingCache) cache
            }                                          
        }    

private void evictAll() {
            if (mCaches != null) {
                IDanmakuIterator it = mCaches.iterator();
                while (it.hasNext()) {
                    BaseDanmaku danmaku = it.next();
                    entryRemoved(true, danmaku, null);
                }
                mCaches.clear();
            }
            mRealSize = 0;
        }


case CLEAR_ALL_CACHES:            
    evictAll();                   //这里
    mCacheTimer.update(mTimer.curr
    mSeekedFlag = true;           
    break;                        

public void requestClearAll() {
            if (mHandler == null) {
                return;
            }
            mHandler.removeMessages(CacheHandler.BUILD_CACHES);
            mHandler.requestCancelCaching();
            mHandler.removeMessages(CacheHandler.CLEAR_ALL_CACHES);
            mHandler.sendEmptyMessage(CacheHandler.CLEAR_ALL_CACHES);//这里发送消息 
        }


```

**Comment by ctiao** [comment]
在master最新代码已修复  d2882df814e7c6b15c6a31a54b5e4607cf3e00e7
maven库版本还未发布

**Comment by ctiao** [comment]
maven或jcenter 0.4.9已发布
