### ISSUE TITLE
CacheManagingDrawTask$CacheManager.clearCache 发生空指针异常

### ISSUE THREAD

**Issue by hss01248** [Bilibili/DanmakuFlameMaster#209]
版本：DanmakuFlameMaster:0.4.6

E/AndroidRuntime: FATAL EXCEPTION: DFM Cache-Building Thread
 java.lang.NullPointerException
at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.clearCache(CacheManagingDrawTask.java:339)
at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager.access$300(CacheManagingDrawTask.java:167)
at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:545)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:177)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ctiao** [comment]
在master最新代码已修复  d2882df814e7c6b15c6a31a54b5e4607cf3e00e7
maven库版本还未发布

**Comment by ctiao** [comment]
maven或jcenter 0.4.9已发布 #205
