### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by gqb** [Bilibili/DanmakuFlameMaster#238]
FATAL EXCEPTION: main
                                                             Process: cn.missevan, PID: 24471
                                                             java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
                                                                 at master.flame.danmaku.danmaku.model.android.SimpleTextCacheStuffer.drawStroke(SimpleTextCacheStuffer.java:64)
                                                                 at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.drawDanmaku(AndroidDisplayer.java:389)
                                                                 at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.draw(AndroidDisplayer.java:289)
                                                                 at master.flame.danmaku.danmaku.model.BaseDanmaku.draw(BaseDanmaku.java:211)
                                                                 at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer.draw(DanmakuRenderer.java:127)
                                                                 at master.flame.danmaku.controller.DrawTask.drawDanmakus(DrawTask.java:341)
                                                                 at master.flame.danmaku.controller.DrawTask.draw(DrawTask.java:232)
                                                                 at master.flame.danmaku.controller.CacheManagingDrawTask.draw(CacheManagingDrawTask.java:122)
                                                                 at master.flame.danmaku.controller.DrawHandler.draw(DrawHandler.java:614)
                                                                 at master.flame.danmaku.ui.widget.DanmakuView.onDraw(DanmakuView.java:311)
                                                                 at android.view.View.draw(View.java:16203)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15126)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.View.draw(View.java:15924)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15121)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                 at android.view.View.getDisplayList(View.java:15149)
                                                                 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
                                                                 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
                                                                 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)

**Comment by RazerGene** [comment]
是canvas.drawText(danmaku.text.toString(), left, top, paint);这句报空指针异常吧，看一下danmaku这个值和danmaku.text。
