### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by HotBitmapGG** [Bilibili/DanmakuFlameMaster#253]
java.lang.NumberFormatException: For input string: "4294967295"
                                                                                  at java.lang.Integer.parseInt(Integer.java:524)
                                                                                  at java.lang.Integer.parseInt(Integer.java:556)
                                                                                  at master.flame.danmaku.danmaku.parser.android.BiliDanmukuParser$XmlContentHandler.startElement(BiliDanmukuParser.java:122)
                                                                                  at org.xmlpull.v1.sax2.Driver.startElement(Driver.java:466)
                                                                                  at org.xmlpull.v1.sax2.Driver.parseSubTree(Driver.java:392)
                                                                                  at org.xmlpull.v1.sax2.Driver.parse(Driver.java:340)
                                                                                  at master.flame.danmaku.danmaku.parser.android.BiliDanmukuParser.parse(BiliDanmukuParser.java:61)
                                                                                  at master.flame.danmaku.danmaku.parser.android.BiliDanmukuParser.parse(BiliDanmukuParser.java:43)
                                                                                  at master.flame.danmaku.danmaku.parser.BaseDanmakuParser.getDanmakus(BaseDanmakuParser.java:82)
                                                                                  at master.flame.danmaku.controller.DrawTask.loadDanmakus(DrawTask.java:305)
                                                                                  at master.flame.danmaku.controller.DrawTask.prepare(DrawTask.java:291)
                                                                                  at master.flame.danmaku.controller.DrawHandler.createDrawTask(DrawHandler.java:553)
                                                                                  at master.flame.danmaku.controller.DrawHandler.prepare(DrawHandler.java:487)
                                                                                  at master.flame.danmaku.controller.DrawHandler.handleMessage(DrawHandler.java:185)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by coffee3689** [comment]
你应该先用Long类型先去parse这个string，然后再强转成int类型，以保证弹幕textColor的赋值

**Comment by ctiao** [comment]
确实有这个问题，以前没有alpha位的，所以不会超过Integer最大值

**Comment by ctiao** [comment]
参考下Color.parseColor的代码
```
public static int parseColor(String colorString) {
        if (colorString.charAt(0) == '#') {
            // Use a long to avoid rollovers on #ffXXXXXX
            long color = Long.parseLong(colorString.substring(1), 16);
            if (colorString.length() == 7) {
                // Set the alpha value
                color |= 0x00000000ff000000;
            } else if (colorString.length() != 9) {
                throw new IllegalArgumentException("Unknown color");
            }
            return (int)color;
        } else {
            Integer color = sColorNameMap.get(colorString.toLowerCase(Locale.ROOT));
            if (color != null) {
                return color;
            }
        }
        throw new IllegalArgumentException("Unknown color");
    }
```

**Comment by ctiao** [comment]
fixed: 8db0f40712d10637d1b61f545797560352bfd379

**Comment by HotBitmapGG** [comment]
@ctiao 感谢跳跳大神，之前确实没这个问题。
