### ISSUE TITLE
master.flame.danmaku.danmaku.model.GlobalFlagValues.FILTER_RESET_FLAG' on a null object reference

### ISSUE THREAD

**Issue by gincoo** [Bilibili/DanmakuFlameMaster#317]
MobUncaughtExceptionHandler: Attempt to read from field 'int master.flame.danmaku.danmaku.model.GlobalFlagValues.FILTER_RESET_FLAG' on a null object reference
                                                                                  java.lang.NullPointerException: Attempt to read from field 'int master.flame.danmaku.danmaku.model.GlobalFlagValues.FILTER_RESET_FLAG' on a null object reference
                                                                                      at master.flame.danmaku.danmaku.model.BaseDanmaku.hasPassedFilter(BaseDanmaku.java:279)
                                                                                      at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler$1.accept(CacheManagingDrawTask.java:698)
                                                                                      at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler$1.accept(CacheManagingDrawTask.java:692)
                                                                                      at master.flame.danmaku.danmaku.model.android.Danmakus.forEach(Danmakus.java:296)
                                                                                      at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.preMeasure(CacheManagingDrawTask.java:692)
                                                                                      at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.prepareCaches(CacheManagingDrawTask.java:716)
                                                                                      at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:539)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mrrobot97** [comment]
+1

**Comment by zou-xian-liang** [comment]
@mrrobot97 
我在解析弹幕数据的时候给每个弹幕设置flags好像可以了
BaseDanmaku item = mContext.mDanmakuFactory.createDanmaku(BaseDanmaku.TYPE_SCROLL_RL,mContext);

item.flags = new GlobalFlagValues();
