### ISSUE TITLE
thread没有自动释放

### ISSUE THREAD

**Issue by meanliang** [Bilibili/DanmakuFlameMaster#324]
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at e.a.a.a.c.p(DrawHandler.java:429)
	at e.a.a.a.c.handleMessage(DrawHandler.java:262)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)

最近我们app搜集的崩溃堆栈中，这个堆栈特别多，从代码上分析是DrawHandler创建线程导致了OOM。从我跟踪debug来看，的确有时候有很多线程没有释放，不过还没找到复现的规律，不知道这个问题官方有没有关注到

**Comment by ctiao** [comment]
不使用之后需要主动调用 release方法
