### ISSUE TITLE
seekTo以后报空指针

### ISSUE THREAD

**Issue by huozhihao** [Bilibili/DanmakuFlameMaster#327]
java.lang.NullPointerException: Attempt to read from field 'master.flame.danmaku.danmaku.model.GlobalFlagValues master.flame.danmaku.danmaku.model.android.DanmakuContext.mGlobalFlagValues' on a null object reference
                                                                             at master.flame.danmaku.controller.DrawHandler.handleMessage(DrawHandler.java:237)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mrrobot97** [comment]
+1

**Comment by IceDcap** [comment]
+1

**Comment by Kimxu** [comment]
+1

**Comment by IceDcap** [comment]
GlobalFlagValues是DanmakuContext对象的成员，它是一个封装了全局标识值的对象，一旦DanmakuContext对象被回收的话通过消息机制进行异步回调的话必然导致空指针，所以在操作DanmakuView时，不仅要判断DanmakuView是否为空而且还有判断DanmakuView.getConfig()是否为空，如果为空重新配置DanmakuView然后在进行相应的操作
