### ISSUE TITLE
Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference

### ISSUE THREAD

**Issue by whoislxy** [Bilibili/DanmakuFlameMaster#367]
非常感谢B站大佬提供此库，使用过程中出现空指针异常，由于是线上环境，取到的日志是混淆过的，希望大佬能给出建议，谢谢
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
	at android.widget.TextView.onMeasure(TextView.java:7874)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1082)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:614)
	at android.view.View.measure(View.java:18563)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1082)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:614)
	at android.view.View.measure(View.java:18563)
	at master.flame.danmaku.danmaku.model.android.k$a.a(SourceFile:28)
	at master.flame.danmaku.danmaku.model.android.k.a(SourceFile:85)
	at master.flame.danmaku.danmaku.model.android.a.a(SourceFile:526)
	at master.flame.danmaku.danmaku.model.android.a.b(SourceFile:519)
	at master.flame.danmaku.danmaku.model.d.a(SourceFile:239)
	at master.flame.danmaku.danmaku.model.q.a(SourceFile:113)
	at master.flame.danmaku.a.a$a$a.a(SourceFile:872)
	at master.flame.danmaku.a.a$a$a.b(SourceFile:946)
	at master.flame.danmaku.a.a$a$a.handleMessage(SourceFile:578)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by erleizh** [comment]
+1

```
java.lang.NullPointerException Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
1 android.widget.TextView.onMeasure(TextView.java:8257)
2 android.view.View.measure(View.java:22024)
3 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6582)
4 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
5 android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
6 android.widget.LinearLayout.onMeasure(LinearLayout.java:687)
7 android.view.View.measure(View.java:22024)
8 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6582)
9 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
10 android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
11 android.widget.LinearLayout.onMeasure(LinearLayout.java:687)
12 android.view.View.measure(View.java:22024)
13 master.flame.danmaku.danmaku.model.android.ViewCacheStuffer$ViewHolder.measure(Unknown Source:2)
14 master.flame.danmaku.danmaku.model.android.ViewCacheStuffer.measure(Unknown Source:75)
15 master.flame.danmaku.danmaku.model.android.AndroidDisplayer.calcPaintWH(Unknown Source:2)
16 master.flame.danmaku.danmaku.model.android.AndroidDisplayer.measure(Unknown Source:18)
17 master.flame.danmaku.danmaku.model.BaseDanmaku.measure(Unknown Source:0)
18 master.flame.danmaku.danmaku.model.R2LDanmaku.measure(Unknown Source:0)
19 master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.buildCache(Unknown Source:14)
20 master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.addDanmakuAndBuildCache(Unknown Source:63)
21 master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(Unknown Source:269)
22 android.os.Handler.dispatchMessage(Handler.java:105)
23 android.os.Looper.loop(Looper.java:164)
24 android.os.HandlerThread.run(HandlerThread.java:65)


```

**Comment by jianglinair** [comment]
+1
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
        at android.widget.TextView.onMeasure(TextView.java:8971)
        at android.view.View.measure(View.java:23434)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6831)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1209)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:23434)
        at master.flame.danmaku.danmaku.model.android.ViewCacheStuffer$ViewHolder.measure(ViewCacheStuffer.java:28)
        at master.flame.danmaku.danmaku.model.android.ViewCacheStuffer.measure(ViewCacheStuffer.java:85)
        at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.calcPaintWH(AndroidDisplayer.java:516)
        at master.flame.danmaku.danmaku.model.android.AndroidDisplayer.measure(AndroidDisplayer.java:509)
        at master.flame.danmaku.danmaku.model.BaseDanmaku.measure(BaseDanmaku.java:235)
        at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer$Consumer.accept(DanmakuRenderer.java:73)
        at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer$Consumer.accept(DanmakuRenderer.java:32)
        at master.flame.danmaku.danmaku.model.android.Danmakus.forEach(Danmakus.java:296)
        at master.flame.danmaku.danmaku.model.android.Danmakus.forEachSync(Danmakus.java:283)
        at master.flame.danmaku.danmaku.renderer.android.DanmakuRenderer.draw(DanmakuRenderer.java:169)
        at master.flame.danmaku.controller.DrawTask.drawDanmakus(DrawTask.java:387)
        at master.flame.danmaku.controller.DrawTask.draw(DrawTask.java:260)
        at master.flame.danmaku.controller.CacheManagingDrawTask.draw(CacheManagingDrawTask.java:118)
        at master.flame.danmaku.controller.DrawHandler.draw(DrawHandler.java:727)
        at master.flame.danmaku.ui.widget.DanmakuView.onDraw(DanmakuView.java:325)
        at android.view.View.draw(View.java:20463)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
        at android.view.View.updateDisplayListIfDirty(View.java:19234)
