### ISSUE TITLE
友盟上的崩溃。我的代码确定没问题，是咱们的弹幕库有问题。

### ISSUE THREAD

**Issue by taishuhongye** [Bilibili/DanmakuFlameMaster#428]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:456)
    at android.view.View.measure(View.java:23434)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6831)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1209)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
    at android.view.View.measure(View.java:23434)
    at master.flame.danmaku.b.b.a.k$a.a(ViewCacheStuffer.java:28)
    at master.flame.danmaku.b.b.a.k.a(ViewCacheStuffer.java:85)
    at master.flame.danmaku.b.b.a.a.a(AndroidDisplayer.java:526)
    at master.flame.danmaku.b.b.a.a.b(AndroidDisplayer.java:519)
    at master.flame.danmaku.b.b.d.a(BaseDanmaku.java:239)
    at master.flame.danmaku.b.b.p.a(R2LDanmaku.java:113)
    at master.flame.danmaku.a.a$a$a.a(CacheManagingDrawTask.java:872)
    at master.flame.danmaku.a.a$a$a.b(CacheManagingDrawTask.java:946)
    at master.flame.danmaku.a.a$a$a.handleMessage(CacheManagingDrawTask.java:557)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by taishuhongye** [comment]
不维护了吧

**Comment by taishuhongye** [comment]
谁有没有稳定一点的库推荐一下的
