### ISSUE TITLE
反馈一个崩溃

### ISSUE THREAD

**Issue by zaze8736** [Bilibili/DanmakuFlameMaster#76]
java.lang.IllegalArgumentException
       at android.view.Surface.nativeUnlockCanvasAndPost(Surface.java)
       at android.view.Surface.unlockCanvasAndPost(Surface.java:255)
       at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:844)
       at master.flame.danmaku.ui.widget.DanmakuSurfaceView.drawDanmakus()
       at master.flame.danmaku.controller.DrawHandler.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ctiao** [comment]
推荐用最新的代码 DanmakuView代替DanmakuSurfaceView

**Comment by zaze8736** [comment]
反复进出时，logcat还会打印以下的log
Exception locking surface java.lang.IllegalStateException: Surface has already been released.
            at android.view.Surface.checkNotReleasedLocked(Surface.java:423)
            at android.view.Surface.lockCanvas(Surface.java:247)
            at android.view.SurfaceView$4.internalLockCanvas(SurfaceView.java:822)
            at android.view.SurfaceView$4.lockCanvas(SurfaceView.java:790)
            at master.flame.danmaku.ui.widget.DanmakuSurfaceView.drawDanmakus(DanmakuSurfaceView.java:240)
            at master.flame.danmaku.controller.DrawHandler$2.run(DrawHandler.java:255)

**Comment by zaze8736** [comment]
我更新到最新的库，再看看
