### ISSUE TITLE
使用0.3.1版本在弹幕release时依旧出现ANR

### ISSUE THREAD

**Issue by xiaojianan** [Bilibili/DanmakuFlameMaster#87]
亲，使用最新版的0.3.1，直接进行release，依旧会出现ANR。

**Comment by ctiao** [comment]
什么情况下调用release(), 能否提供相应重现代码

**Comment by xiaojianan** [comment]
使用fragment播放视频时，关闭fragment，在fragment的onDestory()中调用release，会出现ANR，没有其他附加条件。
代码就是onDestory中执行：
if (mDanmakuView != null) {
	mDanmakuView.release();
}

**Comment by xiaojianan** [comment]
0.2.8版本无此问题，只在最新版出现该ANR

**Comment by ctiao** [comment]
在DDMS里的线程查看里 看看main线程卡在哪里， 还有几个DFM相关的线程存在?

**Comment by ctiao** [comment]
无法重现，暂时关闭

**Comment by aheadlcx** [comment]
能重现，0.9.25 版本，anr log 如下：目前是主线程调用的 danmakuview.release

````java
at android.os.MessageQueue.nativeWake(Native method)
  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:589)
  - locked <0x075f34fa> (a android.os.MessageQueue)
  at android.os.Handler.enqueueMessage(Handler.java:661)
  at android.os.Handler.sendMessageAtTime(Handler.java:630)
  at android.os.Handler.sendMessageDelayed(Handler.java:600)
  at android.os.Handler.sendEmptyMessageDelayed(Handler.java:564)
  at android.os.Handler.sendEmptyMessage(Handler.java:549)
  at master.flame.danmaku.controller.DrawHandler.quit(DrawHandler.java:194)
  at master.flame.danmaku.ui.widget.DanmakuView.stopDraw(DanmakuView.java:177)
  - locked <0x04eccec2> (a master.flame.danmaku.ui.widget.DanmakuView)
  at master.flame.danmaku.ui.widget.DanmakuView.stop(DanmakuView.java:166)
  at master.flame.danmaku.ui.widget.DanmakuView.release(DanmakuView.java:160)
````
